name: llvm-build

on:
  workflow_dispatch:
#  schedule:
#    - cron: '0 18 24 1 *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
#      - name: Set Swap Space
#        uses: pierotofy/set-swap-space@master
#        with:
#          swap-size-gb: 13
      - name: Check out repository
        uses: actions/checkout@v6
      - name: Cleanup
#        if: ${{ 'true' == 'false' }}
        run: |
          sh ./cleanup.sh
      - name: Prepare for build
        run: |
           echo "USERID=$(id -u $(whoami))" >> $GITHUB_ENV
           gh release download --repo mtak-misc/archive --pattern "llvm.zip"
           unzip llvm.zip

           git clone --depth 1 https://gitlab.archlinux.org/archlinux/packaging/packages/linux-zen.git
           cd linux-zen
           sed -i -e '/echo "Prepared $pkgbase version $(<version)"/a \ \ scripts/config -d CONFIG_LTO_NONE' PKGBUILD
           sed -i -e '/echo "Prepared $pkgbase version $(<version)"/a \ \ scripts/config -e CONFIG_LTO_CLANG_FULL' PKGBUILD
           sed -i -e '/echo "Prepared $pkgbase version $(<version)"/a \ \ scripts/config -d CONFIG_LTO_CLANG_THIN' PKGBUILD
           sed -i -e 's/make /make LLVM=1 LLVM_IAS=1 /g' PKGBUILD
#           sed -i -e 's/xz/xz llvm lld clang/g' PKGBUILD
#           curl -LO https://raw.githubusercontent.com/Frogging-Family/linux-tkg/master/linux-tkg-patches/6.3/0013-optimize_harder_O3.patch           
#           sed -i -e '/echo "Setting config..."/i \ \ patch -Np1 -i ../../0013-optimize_harder_O3.patch' PKGBUILD
#           sed -i -e '/echo "Prepared $pkgbase version $(<version)"/a \ \ scripts/config --set-str DEFAULT_TCP_CONG bbr2' PKGBUILD
#           sed -i -e '/echo "Prepared $pkgbase version $(<version)"/a \ \ scripts/config -e DEFAULT_BBR2' PKGBUILD
#           sed -i -e '/echo "Prepared $pkgbase version $(<version)"/a \ \ scripts/config -d DEFAULT_CUBIC' PKGBUILD
#           sed -i -e '/echo "Prepared $pkgbase version $(<version)"/a \ \ scripts/config -m CONFIG_TCP_CONG_CUBIC' PKGBUILD
#           sed -i -e '/echo "Prepared $pkgbase version $(<version)"/a \ \ scripts/config -e CONFIG_TCP_CONG_BBR2' PKGBUILD
#           sed -i -e '/echo "Prepared $pkgbase version $(<version)"/a \ \ scripts/config -e CONFIG_ZEN_INTERACTIVE' PKGBUILD
#           sed -i -e '/echo "Prepared $pkgbase version $(<version)"/a \ \ scripts/config -e CONFIG_SCHED_PDS' PKGBUILD
#           sed -i -e '/echo "Prepared $pkgbase version $(<version)"/a \ \ scripts/config -d CONFIG_SCHED_BMQ' PKGBUILD
#           sed -i -e '/echo "Prepared $pkgbase version $(<version)"/a \ \ scripts/config -e CONFIG_SCHED_ALT' PKGBUILD
#           sed -i -e '/echo "Prepared $pkgbase version $(<version)"/a \ \ scripts/config -d CONFIG_NUMA' PKGBUILD
        env: 
          USERID: ''
          GH_TOKEN: ${{ secrets.pat }}
#           sed -i -e 's/$_srctag/6.2\/main/g' PKGBUILD
      - name: Build kernel
        uses: docker://archlinux:latest
        with:
          entrypoint: '/bin/sh'
          args: ./build.sh ${{ env.USERID }}
      - uses: actions/upload-artifact@v7
        with:
          name: linux-zen
          path: ${{ github.workspace }}/linux-zen/*.pkg.tar.zst
