name: llvm-build

on:
  workflow_dispatch:
#  schedule:
#    - cron: '0 18 24 1 *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 13
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Check out linux-zen repository
        uses: actions/checkout@v3
        with:
          repository: archlinux/svntogit-packages
          ref: 'packages/linux-zen'
          path: linux-zen
      - name: Prepare for build
        run: |
           cd linux-zen/trunk/
           curl -L https://raw.githubusercontent.com/Frogging-Family/linux-tkg/master/linux-tkg-patches/6.2/0013-optimize_harder_O3.patch -o O3.patch
           sed -i -e '/make olddefconfig/i \ \ scripts/config -d CONFIG_LTO_NONE' PKGBUILD
           sed -i -e '/make olddefconfig/i \ \ scripts/config -e CONFIG_LTO_FULL' PKGBUILD
           sed -i -e '/make olddefconfig/i \ \ scripts/config -d CONFIG_LTO_THIN' PKGBUILD
           sed -i -e 's/make htmldocs all/make LLVM=1 LLVM_IAS=1 htmldocs all/g' PKGBUILD
           sed -i -e 's/git/git llvm lld clang/g' PKGBUILD
      - name: Build kernel
        run: |
           docker run -e USERID=$(id -u $(whoami)) -e GITHUB_TOKEN=${{ secrets.pat }} -v $GITHUB_WORKSPACE:/workspace archlinux:latest /bin/bash /workspace/build.sh
           cp $GITHUB_WORKSPACE/linux-zen/*.pkg.tar.zst /tmp
      - uses: actions/upload-artifact@v3
        with:
          name: linux-zen
          path: /tmp/*.pkg.tar.zst
